[package]
name = "datealgo"
version = "0.0.1"
edition = "2021"
authors = ["Nuutti Kotivuori <naked@iki.fi>"]
description = "Low-level date algorithms for libraries"
keywords = ["calendar", "date", "gregorian", "algorithm"]
categories = ["algorithms", "date-and-time", "no-std", "no-std::no-alloc"]
homepage = "https://github.com/nakedible/datealgo-rs"
repository = "https://github.com/nakedible/datealgo-rs"
license = "MIT OR Apache-2.0"

[features]
default = ["std"]
std = []

[lib]
path = "src/lib.rs"
bench = false

[[bench]]
name = "criterion"
harness = false

[dependencies]
chrono = "0.4.24"
criterion = "0.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
strength_reduce = "0.2.4"
