name: Benchmark pull requests
permissions:
  pull-requests: write
on: [pull_request]
  jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request merge
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
      - uses: boa-dev/criterion-compare-action@v3
        with:
          benchName: basic
          branchName: master
